name: Deploy to Azure Function App - Flex Consumption Plan

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Zip artifact for deployment
        run: |
          cd backend
          zip -r ../test-project-function-app.zip test-project-function-app

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: test-project-function-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Login to Azure (Required for Flex Consumption)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Restart Azure Function App (Fixes Potential Deployment Issues)
        run: |
          az functionapp restart --name test-project-function-app --resource-group testprojectfunctionapp

      - name: Deploy to Azure Functions via ZIP (Required for Flex Consumption)
        run: |
          az functionapp deployment source config-zip \
            --resource-group testprojectfunctionapp \
            --name test-project-function-app \
            --src test-project-function-app.zip
